#![cfg(test)]
//! Full-flow tests for the trustless ShieldedPool using REAL Groth16 proofs
//! (see src/test_fixtures.rs, generated by circom/scripts/gen_fixtures.mjs).

use super::*;
use crate::test_fixtures as fx;
use soroban_sdk::testutils::{Address as _, Ledger};
use soroban_sdk::token::{StellarAssetClient, TokenClient};
use soroban_sdk::{Address, BytesN, Env, Vec};

/// The recipient address the swap fixture's proof is bound to (public signal [6] =
/// recipient_field of this address). unshield tests must pass exactly this address.
fn bound_recipient(env: &Env) -> Address {
    Address::from_string(&soroban_sdk::String::from_str(
        env,
        "CABITVLRUBEUPLACCPI7VFZVUBCNDFJRRUWBWTIJXZ5D2NHVB3LMVM6K",
    ))
}

fn b64(env: &Env, a: &[u8; 64]) -> BytesN<64> { BytesN::from_array(env, a) }
fn b128(env: &Env, a: &[u8; 128]) -> BytesN<128> { BytesN::from_array(env, a) }
fn b32(env: &Env, a: &[u8; 32]) -> BytesN<32> { BytesN::from_array(env, a) }
fn sigs(env: &Env, s: &[[u8; 32]]) -> Vec<BytesN<32>> {
    let mut v = Vec::new(env);
    for x in s.iter() { v.push_back(BytesN::from_array(env, x)); }
    v
}

const HIGH_THRESHOLD: i128 = 1_000_000; // swap_amount (250) stays Tier 1

struct Ctx<'a> {
    pool: ShieldedPoolClient<'a>,
    admin: Address,
    pool_id: Address,
    token: Address,
}

/// init + fund pool + seed the note + trustlessly insert it,
/// leaving current_root == the swap proof's merkle_root.
fn setup(env: &Env) -> Ctx {
    env.mock_all_auths();
    let admin = Address::generate(env);
    let token_admin = Address::generate(env);
    let token = env.register_stellar_asset_contract_v2(token_admin).address();

    let pool_id = env.register(ShieldedPool, ());
    let pool = ShieldedPoolClient::new(env, &pool_id);
    pool.init(&admin, &token, &HIGH_THRESHOLD);

    // back the pool with crypto so claim_swap can pay out
    StellarAssetClient::new(env, &token).mint(&pool_id, &1_000);

    // seed + trustlessly insert the note leaf at index 0
    let note = fx::insert_note_fixture();
    pool.faucet_seed(&b32(env, &note.public_signals[2]));
    pool.insert(&b64(env, &note.a), &b128(env, &note.b), &b64(env, &note.c),
        &sigs(env, note.public_signals));

    Ctx { pool, admin, pool_id, token }
}

#[test]
#[should_panic(expected = "already initialized")]
fn init_cannot_run_twice() {
    let env = Env::default();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let token_admin = Address::generate(&env);
    let token = env.register_stellar_asset_contract_v2(token_admin).address();
    let pool_id = env.register(ShieldedPool, ());
    let pool = ShieldedPoolClient::new(&env, &pool_id);

    pool.init(&admin, &token, &HIGH_THRESHOLD);
    pool.init(&admin, &token, &HIGH_THRESHOLD);
}

#[test]
fn full_confidential_swap_flow() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);

    // after inserting the note, current_root == the swap proof's merkle_root
    let swap = fx::swap_fixture();
    assert_eq!(c.pool.current_root(), b32(&env, &swap.public_signals[3]));
    assert_eq!(c.pool.next_index(), 1);

    // confidential swap (amount 250, Tier 1)
    let refund = b32(&env, &[9u8; 32]);
    let swap_id = c.pool.confidential_swap(
        &b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &refund);
    assert_eq!(swap_id, 1);
    assert!(c.pool.get_payout(&swap_id).status == SwapStatus::Pending);
    assert_eq!(c.pool.get_payout(&swap_id).amount, 250);

    // trustlessly insert the change note (index 1)
    let change = fx::insert_change_fixture();
    c.pool.insert(&b64(&env, &change.a), &b128(&env, &change.b), &b64(&env, &change.c),
        &sigs(&env, change.public_signals));
    assert_eq!(c.pool.next_index(), 2);

    // admin claims the swapped crypto to the treasury
    c.pool.claim_swap(&swap_id);
    assert!(c.pool.get_payout(&swap_id).status == SwapStatus::Completed);

    let tok = TokenClient::new(&env, &c.token);
    assert_eq!(tok.balance(&c.admin), 250);
    assert_eq!(tok.balance(&c.pool_id), 750);
}

#[test]
#[should_panic(expected = "nullifier already spent")]
fn double_spend_rejected() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let swap = fx::swap_fixture();
    let refund = b32(&env, &[9u8; 32]);
    c.pool.confidential_swap(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &refund);
    c.pool.confidential_swap(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &refund);
}

#[test]
#[should_panic(expected = "unknown merkle root")]
fn swap_with_uninserted_root_rejected() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let token_admin = Address::generate(&env);
    let token = env.register_stellar_asset_contract_v2(token_admin).address();
    let pool_id = env.register(ShieldedPool, ());
    let pool = ShieldedPoolClient::new(&env, &pool_id);
    pool.init(&admin, &token, &HIGH_THRESHOLD);

    let swap = fx::swap_fixture();
    pool.confidential_swap(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &b32(&env, &[9u8; 32]));
}

#[test]
fn refund_after_timeout() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let swap = fx::swap_fixture();
    let swap_id = c.pool.confidential_swap(&b64(&env, &swap.a), &b128(&env, &swap.b),
        &b64(&env, &swap.c), &sigs(&env, swap.public_signals), &b32(&env, &[9u8; 32]));

    env.ledger().with_mut(|l| l.timestamp += 3601);
    c.pool.refund_swap(&swap_id);
    assert!(c.pool.get_payout(&swap_id).status == SwapStatus::Refunded);
}

#[test]
fn unshield_pays_recipient_and_nullifies() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let swap = fx::swap_fixture(); // proves a note worth >= 250, amount = 250
    let recipient = bound_recipient(&env);

    c.pool.unshield(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &recipient);

    // crypto landed in the recipient wallet; pool retains the rest
    let tok = TokenClient::new(&env, &c.token);
    assert_eq!(tok.balance(&recipient), 250);
    assert_eq!(tok.balance(&c.pool_id), 750);
}

#[test]
fn shielded_transfer_enqueues_two_outputs() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let t = fx::transfer_fixture(); // spends the seed note (index 0) -> recipient + change
    c.pool.shielded_transfer(&b64(&env, &t.a), &b128(&env, &t.b), &b64(&env, &t.c), &sigs(&env, t.public_signals));
    // transfer enqueues both outputs (no insert here) -> tree index unchanged
    assert_eq!(c.pool.next_index(), 1);
}

#[test]
#[should_panic(expected = "nullifier already spent")]
fn shielded_transfer_double_spend_rejected() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let t = fx::transfer_fixture();
    c.pool.shielded_transfer(&b64(&env, &t.a), &b128(&env, &t.b), &b64(&env, &t.c), &sigs(&env, t.public_signals));
    c.pool.shielded_transfer(&b64(&env, &t.a), &b128(&env, &t.b), &b64(&env, &t.c), &sigs(&env, t.public_signals));
}

#[test]
#[should_panic(expected = "nullifier already spent")]
fn unshield_then_swap_same_note_rejected() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let swap = fx::swap_fixture();
    let recipient = bound_recipient(&env);
    c.pool.unshield(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &recipient);
    // reusing the same note (nullifier) for a swap must fail
    c.pool.confidential_swap(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &b32(&env, &[9u8; 32]));
}

// ── Recipient-binding cross-validation ───────────────────────────────────────
// The browser prover computes recipient = int_be(sha256(xdr(address))) mod r and
// feeds it as public signal [6]; the contract recomputes it from the passed Address.
// These MUST match bit-for-bit. The expected values below were produced by the JS
// path (@stellar/stellar-base Address.toScVal().toXDR() → sha256 → mod r) so this
// test fails loudly if the two encodings ever diverge.
#[test]
fn recipient_field_matches_js() {
    use soroban_sdk::{String as SorString};
    let env = Env::default();
    let addr = Address::from_string(&SorString::from_str(
        &env,
        "CABITVLRUBEUPLACCPI7VFZVUBCNDFJRRUWBWTIJXZ5D2NHVB3LMVM6K",
    ));

    // 1. XDR of the address ScVal must match the JS Address.toScVal().toXDR().
    let expected_xdr: [u8; 40] = [
        0x00, 0x00, 0x00, 0x12, 0x00, 0x00, 0x00, 0x01, 0x02, 0x89, 0xd5, 0x71, 0xa0, 0x49, 0x47, 0xac,
        0x02, 0x13, 0xd1, 0xfa, 0x97, 0x35, 0xa0, 0x44, 0xd1, 0x95, 0x31, 0x8d, 0x2c, 0x1b, 0x4d, 0x09,
        0xbe, 0x7a, 0x3d, 0x34, 0xf5, 0x0e, 0xd6, 0xca,
    ];
    let xdr = addr.clone().to_xdr(&env);
    assert_eq!(xdr, Bytes::from_array(&env, &expected_xdr), "to_xdr mismatch vs JS");

    // 2. Full field encoding (sha256 → mod r) must match the JS field element.
    let expected_field: [u8; 32] = [
        0x18, 0xd9, 0x7f, 0xd0, 0x38, 0x5b, 0x30, 0xc1, 0xb7, 0x4c, 0x65, 0xe1, 0xb4, 0x69, 0xee, 0x23,
        0xe4, 0x98, 0x30, 0xaa, 0x69, 0x11, 0x22, 0xa3, 0x8b, 0xe8, 0xce, 0xf6, 0x25, 0x84, 0xd1, 0x3d,
    ];
    let got = ShieldedPool::recipient_field(&env, &addr);
    let want = U256::from_be_bytes(&env, &Bytes::from_array(&env, &expected_field));
    assert_eq!(got, want, "recipient_field mismatch vs JS");
}

#[test]
#[should_panic(expected = "recipient not bound to proof")]
fn unshield_to_wrong_recipient_rejected() {
    // The proof is bound to `bound_recipient`; submitting it with any other recipient
    // (e.g. a relayer redirecting funds to itself) must be rejected even though the
    // Groth16 proof itself is valid. This is the anti-front-running guarantee.
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let swap = fx::swap_fixture();
    let attacker = Address::generate(&env);
    c.pool.unshield(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &attacker);
}
