#![cfg(test)]
//! Full-flow tests for the trustless ShieldedPool using REAL Groth16 proofs
//! (see src/test_fixtures.rs, generated by circom/scripts/gen_fixtures.mjs).

use super::*;
use crate::test_fixtures as fx;
use soroban_sdk::testutils::{Address as _, Ledger};
use soroban_sdk::token::{StellarAssetClient, TokenClient};
use soroban_sdk::{Address, BytesN, Env, Vec};

fn b64(env: &Env, a: &[u8; 64]) -> BytesN<64> { BytesN::from_array(env, a) }
fn b128(env: &Env, a: &[u8; 128]) -> BytesN<128> { BytesN::from_array(env, a) }
fn b32(env: &Env, a: &[u8; 32]) -> BytesN<32> { BytesN::from_array(env, a) }
fn sigs(env: &Env, s: &[[u8; 32]]) -> Vec<BytesN<32>> {
    let mut v = Vec::new(env);
    for x in s.iter() { v.push_back(BytesN::from_array(env, x)); }
    v
}

const HIGH_THRESHOLD: i128 = 1_000_000; // swap_amount (250) stays Tier 1

struct Ctx<'a> {
    pool: ShieldedPoolClient<'a>,
    admin: Address,
    pool_id: Address,
    token: Address,
}

/// init + fund pool + seed the note + trustlessly insert it,
/// leaving current_root == the swap proof's merkle_root.
fn setup(env: &Env) -> Ctx {
    env.mock_all_auths();
    let admin = Address::generate(env);
    let token_admin = Address::generate(env);
    let token = env.register_stellar_asset_contract_v2(token_admin).address();

    let pool_id = env.register(ShieldedPool, ());
    let pool = ShieldedPoolClient::new(env, &pool_id);
    pool.init(&admin, &token, &HIGH_THRESHOLD);

    // back the pool with crypto so claim_swap can pay out
    StellarAssetClient::new(env, &token).mint(&pool_id, &1_000);

    // seed + trustlessly insert the note leaf at index 0
    let note = fx::insert_note_fixture();
    pool.faucet_seed(&b32(env, &note.public_signals[2]));
    pool.insert(&b64(env, &note.a), &b128(env, &note.b), &b64(env, &note.c),
        &sigs(env, note.public_signals));

    Ctx { pool, admin, pool_id, token }
}

#[test]
fn full_confidential_swap_flow() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);

    // after inserting the note, current_root == the swap proof's merkle_root
    let swap = fx::swap_fixture();
    assert_eq!(c.pool.current_root(), b32(&env, &swap.public_signals[3]));
    assert_eq!(c.pool.next_index(), 1);

    // confidential swap (amount 250, Tier 1)
    let refund = b32(&env, &[9u8; 32]);
    let swap_id = c.pool.confidential_swap(
        &b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &refund);
    assert_eq!(swap_id, 1);
    assert!(c.pool.get_payout(&swap_id).status == SwapStatus::Pending);
    assert_eq!(c.pool.get_payout(&swap_id).amount, 250);

    // trustlessly insert the change note (index 1)
    let change = fx::insert_change_fixture();
    c.pool.insert(&b64(&env, &change.a), &b128(&env, &change.b), &b64(&env, &change.c),
        &sigs(&env, change.public_signals));
    assert_eq!(c.pool.next_index(), 2);

    // admin claims the swapped crypto to the treasury
    c.pool.claim_swap(&swap_id);
    assert!(c.pool.get_payout(&swap_id).status == SwapStatus::Completed);

    let tok = TokenClient::new(&env, &c.token);
    assert_eq!(tok.balance(&c.admin), 250);
    assert_eq!(tok.balance(&c.pool_id), 750);
}

#[test]
#[should_panic(expected = "nullifier already spent")]
fn double_spend_rejected() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let swap = fx::swap_fixture();
    let refund = b32(&env, &[9u8; 32]);
    c.pool.confidential_swap(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &refund);
    c.pool.confidential_swap(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &refund);
}

#[test]
#[should_panic(expected = "unknown merkle root")]
fn swap_with_uninserted_root_rejected() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    env.mock_all_auths();
    let admin = Address::generate(&env);
    let token_admin = Address::generate(&env);
    let token = env.register_stellar_asset_contract_v2(token_admin).address();
    let pool_id = env.register(ShieldedPool, ());
    let pool = ShieldedPoolClient::new(&env, &pool_id);
    pool.init(&admin, &token, &HIGH_THRESHOLD);

    let swap = fx::swap_fixture();
    pool.confidential_swap(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &b32(&env, &[9u8; 32]));
}

#[test]
fn refund_after_timeout() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let swap = fx::swap_fixture();
    let swap_id = c.pool.confidential_swap(&b64(&env, &swap.a), &b128(&env, &swap.b),
        &b64(&env, &swap.c), &sigs(&env, swap.public_signals), &b32(&env, &[9u8; 32]));

    env.ledger().with_mut(|l| l.timestamp += 3601);
    c.pool.refund_swap(&swap_id);
    assert!(c.pool.get_payout(&swap_id).status == SwapStatus::Refunded);
}

#[test]
fn unshield_pays_recipient_and_nullifies() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let swap = fx::swap_fixture(); // proves a note worth >= 250, amount = 250
    let recipient = Address::generate(&env);

    c.pool.unshield(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &recipient);

    // crypto landed in the recipient wallet; pool retains the rest
    let tok = TokenClient::new(&env, &c.token);
    assert_eq!(tok.balance(&recipient), 250);
    assert_eq!(tok.balance(&c.pool_id), 750);
}

#[test]
fn shielded_transfer_enqueues_two_outputs() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let t = fx::transfer_fixture(); // spends the seed note (index 0) -> recipient + change
    c.pool.shielded_transfer(&b64(&env, &t.a), &b128(&env, &t.b), &b64(&env, &t.c), &sigs(&env, t.public_signals));
    // transfer enqueues both outputs (no insert here) -> tree index unchanged
    assert_eq!(c.pool.next_index(), 1);
}

#[test]
#[should_panic(expected = "nullifier already spent")]
fn shielded_transfer_double_spend_rejected() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let t = fx::transfer_fixture();
    c.pool.shielded_transfer(&b64(&env, &t.a), &b128(&env, &t.b), &b64(&env, &t.c), &sigs(&env, t.public_signals));
    c.pool.shielded_transfer(&b64(&env, &t.a), &b128(&env, &t.b), &b64(&env, &t.c), &sigs(&env, t.public_signals));
}

#[test]
#[should_panic(expected = "nullifier already spent")]
fn unshield_then_swap_same_note_rejected() {
    let env = Env::default();
    env.cost_estimate().budget().reset_unlimited();
    let c = setup(&env);
    let swap = fx::swap_fixture();
    let recipient = Address::generate(&env);
    c.pool.unshield(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &recipient);
    // reusing the same note (nullifier) for a swap must fail
    c.pool.confidential_swap(&b64(&env, &swap.a), &b128(&env, &swap.b), &b64(&env, &swap.c),
        &sigs(&env, swap.public_signals), &b32(&env, &[9u8; 32]));
}
