// Extract circomlib's BASE Poseidon parameters for t=3 (arity-2 hash) and emit a
// Rust constants module for the Soroban contract, plus a known-answer vector.
//
// The Soroban host fn `poseidon_permutation` applies the STANDARD Poseidon-1
// permutation given (field, t, d, rounds_f, rounds_p, mds, round_constants).
// circomlib uses t=3, RF=8, RP=57, d=5 with these exact C (flat 195) and M (3x3).
import { writeFileSync, readFileSync } from "fs";
import { buildPoseidon } from "circomlibjs";
const constants = JSON.parse(
  readFileSync("node_modules/circomlibjs/src/poseidon_constants.json", "utf8")
);

const T = 3, RF = 8, RP = 57, D = 5;
const idx = T - 2;

// unstringify hex -> BigInt
const toBig = (s) => BigInt(s);
const Cflat = constants.C[idx].map(toBig);   // length (RF+RP)*T = 195
const M = constants.M[idx].map((row) => row.map(toBig)); // T x T

if (Cflat.length !== (RF + RP) * T) throw new Error(`C length ${Cflat.length} != ${(RF+RP)*T}`);
if (M.length !== T || M.some((r) => r.length !== T)) throw new Error("M shape != TxT");

// reshape C to (RF+RP) rows x T cols
const rows = [];
for (let r = 0; r < RF + RP; r++) rows.push(Cflat.slice(r * T, r * T + T));

const be32 = (x) => {
  let h = x.toString(16).padStart(64, "0");
  return h.match(/.{2}/g).map((b) => "0x" + b).join(", ");
};
const arrLit = (x) => `    [${be32(x)}]`;

let rs = `// AUTO-GENERATED by scripts/export_poseidon_t3.mjs — circomlib Poseidon t=3 (arity-2).\n`;
rs += `// Standard Poseidon-1: field=BN254, t=${T}, d=${D}, rounds_f=${RF}, rounds_p=${RP}.\n`;
rs += `// Fed to soroban_sdk Crypto::poseidon_permutation so on-chain hashing matches the circuit.\n\n`;
rs += `pub const T: u32 = ${T};\npub const D: u32 = ${D};\npub const ROUNDS_F: u32 = ${RF};\npub const ROUNDS_P: u32 = ${RP};\n\n`;
rs += `// MDS matrix M (${T}x${T}), each entry a 32-byte big-endian field element.\n`;
rs += `pub const MDS: [[[u8; 32]; ${T}]; ${T}] = [\n`;
for (const row of M) rs += `  [\n${row.map(arrLit).join(",\n")}\n  ],\n`;
rs += `];\n\n`;
rs += `// Round constants C ((rounds_f+rounds_p)=${RF + RP} rows x ${T} cols).\n`;
rs += `pub const RC: [[[u8; 32]; ${T}]; ${RF + RP}] = [\n`;
for (const row of rows) rs += `  [\n${row.map(arrLit).join(",\n")}\n  ],\n`;
rs += `];\n`;

writeFileSync("build/poseidon_t3_constants.rs", rs);
console.log("wrote build/poseidon_t3_constants.rs");

// known-answer vector for the contract test
const pos = await buildPoseidon();
const kat = (a, b) => pos.F.toString(pos([a, b]));
const vec = { in: ["1", "2"], out: kat(1n, 2n), in2: ["7", "99"], out2: kat(7n, 99n) };
writeFileSync("build/poseidon_t3_kat.json", JSON.stringify(vec, null, 2));
console.log("KAT poseidon([1,2]) =", vec.out);
console.log("KAT poseidon([7,99]) =", vec.out2);
