// Emit src/vk.rs for the contract: both verifying keys as builders into groth16::Vk.
import { readFileSync, writeFileSync } from "fs";

const be32 = (xBig) => {
  let h = (BigInt(xBig) % (2n ** 256n)).toString(16).padStart(64, "0");
  return Uint8Array.from(h.match(/.{2}/g).map((b) => parseInt(b, 16)));
};
const lit = (u8) => `[${Array.from(u8).map((b) => "0x" + b.toString(16).padStart(2, "0")).join(", ")}]`;
const g1 = (p) => lit(new Uint8Array([...be32(p[0]), ...be32(p[1])]));
const g2 = (p) => lit(new Uint8Array([...be32(p[0][1]), ...be32(p[0][0]), ...be32(p[1][1]), ...be32(p[1][0])]));

function builder(fnName, vk) {
  let s = `pub fn ${fnName}(env: &Env) -> Vk {\n`;
  s += `    let mut ic: Vec<Bn254G1Affine> = Vec::new(env);\n`;
  for (const p of vk.IC) s += `    ic.push_back(g1_from(env, &${g1(p)}));\n`;
  s += `    Vk {\n`;
  s += `        alpha1: g1_from(env, &${g1(vk.vk_alpha_1)}),\n`;
  s += `        beta2: g2_from(env, &${g2(vk.vk_beta_2)}),\n`;
  s += `        gamma2: g2_from(env, &${g2(vk.vk_gamma_2)}),\n`;
  s += `        delta2: g2_from(env, &${g2(vk.vk_delta_2)}),\n`;
  s += `        ic,\n    }\n}\n`;
  return s;
}

const swap = JSON.parse(readFileSync("build/confidential_swap_vk.json", "utf8"));
const insert = JSON.parse(readFileSync("build/merkle_insert_vk.json", "utf8"));
const transfer = JSON.parse(readFileSync("build/shielded_transfer_vk.json", "utf8"));

let rs = `// AUTO-GENERATED by scripts/export_vk_rust.mjs — embedded Groth16 verifying keys.\n`;
rs += `use soroban_sdk::{Env, Vec};\nuse soroban_sdk::crypto::bn254::Bn254G1Affine;\n`;
rs += `use crate::groth16::{Vk, g1_from, g2_from};\n\n`;
rs += builder("confidential_swap_vk", swap) + "\n" + builder("merkle_insert_vk", insert) + "\n"
   + builder("shielded_transfer_vk", transfer);
writeFileSync("../contracts/shielded_pool/src/vk.rs", rs);
console.log("wrote contracts/shielded_pool/src/vk.rs");
